[build]
  command = "npm run build"    # Comando para construir o projeto
  publish = ".next"
  node_version = "18.17.1"     # Define uma versão válida do Node.js

[build.environment]
  NODE_ENV = "production"      # Define o ambiente como produção
