[build]
  command = "npm install tailwindcss && npm run build"  # Instala o Tailwind CSS e executa o build
  publish = ".next"
  node_version = "18.17.1"

[build.environment]
  NODE_ENV = "production"
